// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.Api;

#nullable disable

namespace Sample.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260910183745_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataDictionary.Abstractions.Persistence.DictionaryEntry", b =>
                {
                    b.Property<string>("EnumKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("enum_key");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("field_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("code");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("group_name");

                    b.Property<int>("IsActive")
                        .HasColumnType("int")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("bit")
                        .HasColumnName("is_deprecated");

                    b.Property<long>("NumericValue")
                        .HasColumnType("bigint")
                        .HasColumnName("numeric_value");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("EnumKey", "FieldName");

                    b.HasIndex("EnumKey", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_dicionario_dados_enum_key_code_active")
                        .HasFilter("is_active = 1");

                    b.ToTable("tb_dicionario_dados", (string)null);

                    b.HasData(
                        new
                        {
                            EnumKey = "RacaCor",
                            FieldName = "Branca",
                            Code = "B",
                            ContentHash = "0a2ed89f3b69376770586f8bce24ad8557176dc5274b7f602f1e31a568cc962f",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Branca",
                            GroupName = "Cadastro",
                            IsActive = 1,
                            IsDeprecated = false,
                            NumericValue = 1L,
                            SortOrder = 0
                        },
                        new
                        {
                            EnumKey = "RacaCor",
                            FieldName = "Preta",
                            Code = "P",
                            ContentHash = "20ef683e4825f423341ef4f3ff89fcf727b4b2ae37afd03dd2f332703fc8cd28",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Preta",
                            GroupName = "Cadastro",
                            IsActive = 1,
                            IsDeprecated = false,
                            NumericValue = 2L,
                            SortOrder = 1
                        },
                        new
                        {
                            EnumKey = "RacaCor",
                            FieldName = "Parda",
                            Code = "PA",
                            ContentHash = "b38a0a5f55e0268c459aa3e8504104213e6a4b9475ff94ecd25cca790d58239f",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Parda",
                            GroupName = "Cadastro",
                            IsActive = 1,
                            IsDeprecated = false,
                            NumericValue = 3L,
                            SortOrder = 2
                        },
                        new
                        {
                            EnumKey = "RacaCor",
                            FieldName = "Amarela",
                            Code = "AM",
                            ContentHash = "c1381bb9954f3aa46311c5ce3932a41897cddf18c4abf1d70c1b6b8616690d98",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Amarela",
                            GroupName = "Cadastro",
                            IsActive = 1,
                            IsDeprecated = false,
                            NumericValue = 4L,
                            SortOrder = 3
                        },
                        new
                        {
                            EnumKey = "RacaCor",
                            FieldName = "Indigena",
                            Code = "I",
                            ContentHash = "54f7d9099698465c86ebbd8ba0f2d7522f07791fff4d7e02445a50ba947e02e1",
                            CreatedAt = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Indígena",
                            GroupName = "Cadastro",
                            IsActive = 1,
                            IsDeprecated = false,
                            NumericValue = 5L,
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("DataDictionary.Abstractions.Persistence.DictionaryEnumCatalogEntry", b =>
                {
                    b.Property<string>("EnumKey")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("enum_key");

                    b.Property<string>("AssemblyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assembly_name");

                    b.Property<string>("ClrFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clr_full_name");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("group_name");

                    b.Property<DateTimeOffset>("LastSyncAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_sync_at");

                    b.Property<string>("ManifestHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("manifest_hash");

                    b.HasKey("EnumKey");

                    b.ToTable("tb_dicionario_enum", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
