using System.Collections.Immutable;
using System.Text;
using DataDictionary.Generator.Internal;
using DataDictionary.Generator.Model;
using Microsoft.CodeAnalysis;

namespace DataDictionary.Generator;

/// <summary>
/// Emits the generated <c>&lt;ConsumerAssembly&gt;.Generated.DataDictionaryManifest.Default</c>
/// static entry point (<c>contracts/generated-entrypoints-contract.md</c>) from the
/// final, validated <see cref="GeneratorEnumModel"/> set. Every value written is a
/// compile-time literal — no reflection, no attribute inspection, and no assembly
/// scanning occurs when the emitted static initializes, satisfying Constitution
/// Principle IV (zero hot-path reflection).
/// </summary>
internal static class ManifestEmitter
{
    private const string ManifestTypeName = "global::DataDictionary.Abstractions.Manifest.DataDictionaryManifest";
    private const string EnumEntryTypeName = "global::DataDictionary.Abstractions.Manifest.ManifestEnumEntry";
    private const string MemberEntryTypeName = "global::DataDictionary.Abstractions.Manifest.ManifestMemberEntry";

    /// <summary>
    /// Builds the generated source text for <paramref name="enums"/>, or
    /// <see langword="null"/> when there is nothing to emit — per the contract, the
    /// manifest is only emitted "once per compilation that contains at least one valid
    /// marked enum".
    /// </summary>
    internal static string? Emit(Compilation compilation, ImmutableArray<GeneratorEnumModel> enums)
    {
        if (enums.IsDefaultOrEmpty)
        {
            return null;
        }

        var ns = NamespaceSanitizer.ToNamespaceSegment(compilation.AssemblyName ?? string.Empty);

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("// Generated by DataDictionary.Generator. Do not edit by hand.");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").Append(ns).AppendLine(".Generated");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// The compile-time data dictionary manifest for this assembly, generated by");
        builder.AppendLine("    /// DataDictionary.Generator from every valid <c>[DataDictionary]</c>-marked or");
        builder.AppendLine("    /// convention-scanned enum in this compilation.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public static class DataDictionaryManifest");
        builder.AppendLine("    {");
        builder.AppendLine("        /// <summary>The generated manifest instance for this assembly.</summary>");
        builder.Append("        public static readonly ").Append(ManifestTypeName).AppendLine(" Default = new(");
        builder.Append("            global::System.Collections.Immutable.ImmutableArray.Create<").Append(EnumEntryTypeName).AppendLine(">(");

        for (var i = 0; i < enums.Length; i++)
        {
            AppendEnumEntry(builder, enums[i]);
            builder.AppendLine(i == enums.Length - 1 ? string.Empty : ",");
        }

        builder.AppendLine("            )");
        builder.AppendLine("        );");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        return builder.ToString();
    }

    /// <summary>
    /// The generated file's hint name for a given compilation — stable across runs so
    /// the same compilation always regenerates the same file identity.
    /// </summary>
    internal const string HintName = "DataDictionaryManifest.g.cs";

    private static void AppendEnumEntry(StringBuilder builder, GeneratorEnumModel enumModel)
    {
        builder.Append("                new ").Append(EnumEntryTypeName).AppendLine("(");
        builder.Append("                    EnumKey: ").Append(Literal(enumModel.EnumKey)).AppendLine(",");
        builder.Append("                    GroupName: ").Append(Literal(enumModel.GroupName)).AppendLine(",");
        builder.Append("                    ClrFullName: ").Append(Literal(enumModel.ClrFullName)).AppendLine(",");
        builder.Append("                    AssemblyName: ").Append(Literal(enumModel.AssemblyName)).AppendLine(",");
        builder.Append("                    Description: ").Append(Literal(enumModel.Description)).AppendLine(",");
        builder.Append("                    IsFlags: ").Append(BoolLiteral(enumModel.IsFlags)).AppendLine(",");

        if (enumModel.Members.IsDefaultOrEmpty)
        {
            builder.Append("                    Members: global::System.Collections.Immutable.ImmutableArray<").Append(MemberEntryTypeName).Append(">.Empty");
        }
        else
        {
            builder.Append("                    Members: global::System.Collections.Immutable.ImmutableArray.Create<").Append(MemberEntryTypeName).AppendLine(">(");

            for (var i = 0; i < enumModel.Members.Length; i++)
            {
                AppendMemberEntry(builder, enumModel.Members[i]);
                builder.AppendLine(i == enumModel.Members.Length - 1 ? string.Empty : ",");
            }

            builder.Append("                    )");
        }

        builder.AppendLine();
        builder.Append("                )");
    }

    private static void AppendMemberEntry(StringBuilder builder, GeneratorMemberModel member)
    {
        builder.Append("                        new ").Append(MemberEntryTypeName).AppendLine("(");
        builder.Append("                            FieldName: ").Append(Literal(member.FieldName)).AppendLine(",");
        builder.Append("                            Code: ").Append(Literal(member.Code)).AppendLine(",");
        builder.Append("                            NumericValue: ").Append(member.NumericValue).AppendLine("L,");
        builder.Append("                            Description: ").Append(Literal(member.Description)).AppendLine(",");
        builder.Append("                            GroupName: ").Append(Literal(member.GroupName)).AppendLine(",");
        builder.Append("                            IsDeprecated: ").Append(BoolLiteral(member.IsDeprecated)).AppendLine(",");
        builder.Append("                            SortOrder: ").Append(member.SortOrder).AppendLine();
        builder.Append("                        )");
    }

    private static string Literal(string? value) =>
        value is null ? "null" : Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);

    private static string BoolLiteral(bool value) => value ? "true" : "false";
}
